CREATE TABLE IF NOT EXISTS etl_run (
    run_id VARCHAR(80) PRIMARY KEY,
    dataset_code VARCHAR(80) NOT NULL,
    source_system VARCHAR(80) NOT NULL,
    source_file TEXT NOT NULL,
    archived_file TEXT,
    file_sha256 CHAR(64) NOT NULL,
    period_start VARCHAR(10),
    period_end VARCHAR(10),
    started_at VARCHAR(40) NOT NULL,
    finished_at VARCHAR(40),
    status VARCHAR(16) NOT NULL,
    rows_read BIGINT NOT NULL DEFAULT 0,
    rows_inserted BIGINT NOT NULL DEFAULT 0,
    rows_updated BIGINT NOT NULL DEFAULT 0,
    rows_unchanged BIGINT NOT NULL DEFAULT 0,
    rows_failed BIGINT NOT NULL DEFAULT 0,
    rows_duplicates BIGINT NOT NULL DEFAULT 0,
    error_message TEXT,
    KEY idx_etl_run_dataset_started (dataset_code, started_at),
    KEY idx_etl_run_dataset_period (dataset_code, period_start, period_end, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS collection_run (
    collection_run_id VARCHAR(80) PRIMARY KEY,
    dataset_code VARCHAR(80) NOT NULL,
    period_start VARCHAR(10) NOT NULL,
    period_end VARCHAR(10) NOT NULL,
    started_at VARCHAR(40) NOT NULL,
    finished_at VARCHAR(40),
    status VARCHAR(16) NOT NULL,
    expected_files BIGINT,
    produced_files BIGINT NOT NULL DEFAULT 0,
    imported_files BIGINT NOT NULL DEFAULT 0,
    source_files LONGTEXT NOT NULL,
    etl_run_ids LONGTEXT NOT NULL,
    error_message TEXT,
    KEY idx_collection_run_dataset_period (dataset_code, period_start, period_end, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tr_source_snapshot (
    snapshot_id VARCHAR(64) PRIMARY KEY,
    dataset_code VARCHAR(80) NOT NULL,
    period_start VARCHAR(10) NOT NULL,
    period_end VARCHAR(10) NOT NULL,
    etl_run_id VARCHAR(80) NOT NULL,
    created_at VARCHAR(40) NOT NULL,
    filename VARCHAR(255) NOT NULL,
    sha256 CHAR(64) NOT NULL,
    row_count BIGINT NOT NULL,
    workbook LONGBLOB NOT NULL,
    KEY idx_tr_source_snapshot_dataset_period (dataset_code, period_start, period_end, created_at),
    KEY idx_tr_source_snapshot_etl_run (etl_run_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tr_source_row (
    snapshot_id VARCHAR(64) NOT NULL,
    source_row_number BIGINT NOT NULL,
    cells_json LONGTEXT NOT NULL,
    PRIMARY KEY (snapshot_id, source_row_number),
    CONSTRAINT fk_tr_source_row_snapshot
        FOREIGN KEY (snapshot_id) REFERENCES tr_source_snapshot(snapshot_id)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- BEGIN FIXED RAW TABLES (generated from config/raw_columns.json)
CREATE TABLE IF NOT EXISTS `terminal_material_names` (
    `物料名称` VARCHAR(255) COLLATE utf8mb4_bin NOT NULL,
    `划分类型` LONGTEXT,
    PRIMARY KEY (`物料名称`)
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `terminal_material_names_version` (
    version_id BIGINT PRIMARY KEY AUTO_INCREMENT,
    source_record_id VARCHAR(255) COLLATE utf8mb4_bin NOT NULL,
    run_id VARCHAR(80) NOT NULL,
    row_hash CHAR(64) NOT NULL,
    source_data LONGTEXT NOT NULL,
    observed_at VARCHAR(40) NOT NULL,
    UNIQUE KEY uk_version_record_hash (source_record_id, row_hash),
    KEY idx_version_run (run_id),
    FOREIGN KEY (run_id) REFERENCES etl_run(run_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `integration_removal_order` (
    `工单号` VARCHAR(255) COLLATE utf8mb4_bin NOT NULL,
    `工单主题` LONGTEXT,
    `工单数据来源` LONGTEXT,
    `上游工单号` LONGTEXT,
    `派单时间` LONGTEXT,
    `受理部门` LONGTEXT,
    `工单流向` LONGTEXT,
    `地市` LONGTEXT,
    `区县` LONGTEXT,
    `业务类型` LONGTEXT,
    `工单类型` LONGTEXT,
    `调整类型` LONGTEXT,
    `是否存在关联工单` LONGTEXT,
    `关联工单号` LONGTEXT,
    `工单状态` LONGTEXT,
    `是否超时` LONGTEXT,
    `是否撤单重录` LONGTEXT,
    `首次派单时间` LONGTEXT,
    `首次考核超时时限` LONGTEXT,
    `考核超时时限` LONGTEXT,
    `工单是否及时开通` LONGTEXT,
    `业务开通时间(h)` LONGTEXT,
    `工单历时/小时` LONGTEXT,
    `工单处理时限` LONGTEXT,
    `工单结束时间` LONGTEXT,
    `业务套餐类型` LONGTEXT,
    `业务保障等级` LONGTEXT,
    `计费号/产品实例编号` LONGTEXT,
    `是否派发工程施工` LONGTEXT,
    PRIMARY KEY (`工单号`)
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `integration_removal_order_version` (
    version_id BIGINT PRIMARY KEY AUTO_INCREMENT,
    source_record_id VARCHAR(255) COLLATE utf8mb4_bin NOT NULL,
    run_id VARCHAR(80) NOT NULL,
    row_hash CHAR(64) NOT NULL,
    source_data LONGTEXT NOT NULL,
    observed_at VARCHAR(40) NOT NULL,
    UNIQUE KEY uk_version_record_hash (source_record_id, row_hash),
    KEY idx_version_run (run_id),
    FOREIGN KEY (run_id) REFERENCES etl_run(run_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `eoms_service_removal_order` (
    `派单时间` LONGTEXT,
    `主题` LONGTEXT,
    `工单号` VARCHAR(255) COLLATE utf8mb4_bin NOT NULL,
    `集客系统工单号` LONGTEXT,
    `编排系统工单号` LONGTEXT,
    `派单部门` LONGTEXT,
    `派单人` LONGTEXT,
    `客户编号` LONGTEXT,
    `客户名称` LONGTEXT,
    `所属省份` LONGTEXT,
    `所属地市` LONGTEXT,
    `所属区县` LONGTEXT,
    `所属乡镇街道` LONGTEXT,
    `集团客户级别` LONGTEXT,
    `集团客户行业` LONGTEXT,
    `客户经理` LONGTEXT,
    `客户级别` LONGTEXT,
    `省份名称` LONGTEXT,
    `客户服务等级` LONGTEXT,
    `VIP等级` LONGTEXT,
    `计费编号` LONGTEXT,
    `产品实例号` LONGTEXT,
    `服务大类` LONGTEXT,
    `服务类别` LONGTEXT,
    `工单状态` LONGTEXT,
    `内网服务编号` LONGTEXT,
    `服务要求完成时间` LONGTEXT,
    `内网服务产品类型` LONGTEXT,
    `业务保障等级` LONGTEXT,
    `报结时间` LONGTEXT,
    `是否超时` LONGTEXT,
    `受理部门` LONGTEXT,
    `受理人` LONGTEXT,
    `SLA时限` LONGTEXT,
    `操作类型` LONGTEXT,
    `BBOSS产品订单号` LONGTEXT,
    `BBOSS产品实例标识` LONGTEXT,
    `客户机房地址` LONGTEXT,
    `E组企网套装类型` LONGTEXT,
    `专线卫士套装类型` LONGTEXT,
    `利旧/新增专线` LONGTEXT,
    `关联的互联网专线计费号` LONGTEXT,
    `E企组网技术方案` LONGTEXT,
    `路由器数量` LONGTEXT,
    `交换机数量` LONGTEXT,
    `FTTR数量` LONGTEXT,
    `光插座数量` LONGTEXT,
    `光AP数量` LONGTEXT,
    `服务小类` LONGTEXT,
    `服务内容` LONGTEXT,
    `受理提交时间` LONGTEXT,
    `设备类型` LONGTEXT,
    `终端安装地点详细地址` LONGTEXT,
    `服务质量验证提交时间` LONGTEXT,
    `光纤信息点数` LONGTEXT,
    `终端自服务平台账号` LONGTEXT,
    `网线信息点数` LONGTEXT,
    `终端自服务平台密码` LONGTEXT,
    `终端设备型号` LONGTEXT,
    `受理环节驳回意见` LONGTEXT,
    `报结人` LONGTEXT,
    `报结环节驳回意见` LONGTEXT,
    `报结环节处理方式` LONGTEXT,
    `安装地市` LONGTEXT,
    `安装区县` LONGTEXT,
    PRIMARY KEY (`工单号`)
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `eoms_service_removal_order_version` (
    version_id BIGINT PRIMARY KEY AUTO_INCREMENT,
    source_record_id VARCHAR(255) COLLATE utf8mb4_bin NOT NULL,
    run_id VARCHAR(80) NOT NULL,
    row_hash CHAR(64) NOT NULL,
    source_data LONGTEXT NOT NULL,
    observed_at VARCHAR(40) NOT NULL,
    UNIQUE KEY uk_version_record_hash (source_record_id, row_hash),
    KEY idx_version_run (run_id),
    FOREIGN KEY (run_id) REFERENCES etl_run(run_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `integration_terminal_outbound` (
    `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `地市` LONGTEXT,
    `区县` LONGTEXT,
    `班组名称` LONGTEXT,
    `编号` LONGTEXT,
    `标题` LONGTEXT,
    `操作类型` LONGTEXT,
    `关联单据类型` LONGTEXT,
    `关联单据号` LONGTEXT,
    `领用单编号` LONGTEXT,
    `物料ID` LONGTEXT,
    `物料名称` LONGTEXT,
    `型号` LONGTEXT,
    `计量单位` LONGTEXT,
    `状态` LONGTEXT,
    `厂家` LONGTEXT,
    `新物资数量` LONGTEXT,
    `返修物资数量` LONGTEXT,
    `回收物资数量` LONGTEXT,
    `总数量` LONGTEXT,
    `申请时间` LONGTEXT,
    `申请人` LONGTEXT,
    `确认时间` LONGTEXT,
    `确认人` LONGTEXT
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `integration_terminal_outbound_version` (
    version_id BIGINT PRIMARY KEY AUTO_INCREMENT,
    source_record_id VARCHAR(255) COLLATE utf8mb4_bin NOT NULL,
    run_id VARCHAR(80) NOT NULL,
    row_hash CHAR(64) NOT NULL,
    source_data LONGTEXT NOT NULL,
    observed_at VARCHAR(40) NOT NULL,
    UNIQUE KEY uk_version_record_hash (source_record_id, row_hash),
    KEY idx_version_run (run_id),
    FOREIGN KEY (run_id) REFERENCES etl_run(run_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `integration_terminal_inbound` (
    `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `地市` LONGTEXT,
    `区县` LONGTEXT,
    `班组名称` LONGTEXT,
    `编号` LONGTEXT,
    `标题` LONGTEXT,
    `操作类型` LONGTEXT,
    `关联单据类型` LONGTEXT,
    `关联单据号` LONGTEXT,
    `领用单编号` LONGTEXT,
    `物料ID` LONGTEXT,
    `物料名称` LONGTEXT,
    `型号` LONGTEXT,
    `计量单位` LONGTEXT,
    `状态` LONGTEXT,
    `厂家` LONGTEXT,
    `新物资数量` LONGTEXT,
    `返修物资数量` LONGTEXT,
    `回收物资数量` LONGTEXT,
    `总数量` LONGTEXT,
    `申请时间` LONGTEXT,
    `申请人` LONGTEXT,
    `确认时间` LONGTEXT,
    `确认人` LONGTEXT
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `integration_terminal_inbound_version` (
    version_id BIGINT PRIMARY KEY AUTO_INCREMENT,
    source_record_id VARCHAR(255) COLLATE utf8mb4_bin NOT NULL,
    run_id VARCHAR(80) NOT NULL,
    row_hash CHAR(64) NOT NULL,
    source_data LONGTEXT NOT NULL,
    observed_at VARCHAR(40) NOT NULL,
    UNIQUE KEY uk_version_record_hash (source_record_id, row_hash),
    KEY idx_version_run (run_id),
    FOREIGN KEY (run_id) REFERENCES etl_run(run_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `integration_material_baseline` (
    `物料基准ID` VARCHAR(255) COLLATE utf8mb4_bin NOT NULL,
    `物料名称` LONGTEXT,
    `型号` LONGTEXT,
    `计量单位` LONGTEXT,
    `厂家` LONGTEXT,
    `单价(元)` LONGTEXT,
    `分类` LONGTEXT,
    `终端类型` LONGTEXT,
    `商客终端类型` LONGTEXT,
    `是否主设备` LONGTEXT,
    `设备分类` LONGTEXT,
    `是否为互联网电视盒子/智能网` LONGTEXT,
    `是否为低值易耗品` LONGTEXT,
    `是否核算为其它部门成本` LONGTEXT,
    `其它部门名称` LONGTEXT,
    `用途` LONGTEXT,
    `备注` LONGTEXT,
    `物料名称(供应链)` LONGTEXT,
    `型号(供应链)` LONGTEXT,
    `物料名称(资管)` LONGTEXT,
    `型号(资管)` LONGTEXT,
    `物料名称(网管)` LONGTEXT,
    `型号(网管)` LONGTEXT,
    `修改时间` LONGTEXT,
    `修改人` LONGTEXT,
    PRIMARY KEY (`物料基准ID`)
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `integration_material_baseline_version` (
    version_id BIGINT PRIMARY KEY AUTO_INCREMENT,
    source_record_id VARCHAR(255) COLLATE utf8mb4_bin NOT NULL,
    run_id VARCHAR(80) NOT NULL,
    row_hash CHAR(64) NOT NULL,
    source_data LONGTEXT NOT NULL,
    observed_at VARCHAR(40) NOT NULL,
    UNIQUE KEY uk_version_record_hash (source_record_id, row_hash),
    KEY idx_version_run (run_id),
    FOREIGN KEY (run_id) REFERENCES etl_run(run_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `orch_opening` (
    `订单号` VARCHAR(255) COLLATE utf8mb4_bin NOT NULL,
    `主题` LONGTEXT,
    `订单创建时间` LONGTEXT,
    `订单状态` LONGTEXT,
    `地市` LONGTEXT,
    `区县名称` LONGTEXT,
    `是否点金工单` LONGTEXT,
    `是否快装` LONGTEXT,
    `业务分类` LONGTEXT,
    `业务类型` LONGTEXT,
    `产品名称` LONGTEXT,
    `订单类型` LONGTEXT,
    `需求网络维护等级` LONGTEXT,
    `调整类型` LONGTEXT,
    `产品实例编号` LONGTEXT,
    `专线编号` LONGTEXT,
    `带宽` LONGTEXT,
    `上行带宽` LONGTEXT,
    `上网用途` LONGTEXT,
    `CRM工单号` LONGTEXT,
    `是否撤单重录` LONGTEXT,
    `当前环节` LONGTEXT,
    `当前处理组` LONGTEXT,
    `预约上门时间` LONGTEXT,
    `联调测试时间` LONGTEXT,
    `是否超时` LONGTEXT,
    `超时时间` LONGTEXT,
    `首次派单时间` LONGTEXT,
    `首次考核超时时限` LONGTEXT,
    `考核超时时限` LONGTEXT,
    `工单持续时长` LONGTEXT,
    `当前环节开始时间` LONGTEXT,
    `当前环节持续时长` LONGTEXT,
    `剩余时间` LONGTEXT,
    `工单报结时间` LONGTEXT,
    `订单结束时间` LONGTEXT,
    `订单来源` LONGTEXT,
    `融合工单号` LONGTEXT,
    `客户名称` LONGTEXT,
    `客户编码` LONGTEXT,
    `客户经理` LONGTEXT,
    `集客部联系人联系电话` LONGTEXT,
    `受理人` LONGTEXT,
    `受理人电话` LONGTEXT,
    `报结人` LONGTEXT,
    `报结人电话` LONGTEXT,
    `边缘云专线/三方云专线类型` LONGTEXT,
    `集团客户业务联系人` LONGTEXT,
    `集团客户业务联系人电话` LONGTEXT,
    `集团客户技术联系人` LONGTEXT,
    `集团客户技术联系人电话` LONGTEXT,
    `业务接入标准地址` LONGTEXT,
    `市场网格` LONGTEXT,
    `业务受理耗时` LONGTEXT,
    `方案设计耗时` LONGTEXT,
    `方案审批耗时` LONGTEXT,
    `现网变更耗时` LONGTEXT,
    `业务验证耗时` LONGTEXT,
    `归档报结耗时` LONGTEXT,
    `方案设计处理人` LONGTEXT,
    `资源查询受理人` LONGTEXT,
    `方案审核处理人` LONGTEXT,
    `资源分配受理人` LONGTEXT,
    `配置激活处理人` LONGTEXT,
    `客户端安装处理人` LONGTEXT,
    `业务验证处理人` LONGTEXT,
    `开通结果审核处理人` LONGTEXT,
    `是否派发工程施工` LONGTEXT,
    `施工结果` LONGTEXT,
    `施工耗时` LONGTEXT,
    `点金剩余时间` LONGTEXT,
    `施工费用` LONGTEXT,
    `场所类别` LONGTEXT,
    `A端专线接入区县` LONGTEXT,
    `细分客群类别` LONGTEXT,
    `A端业务接入标准地址` LONGTEXT,
    `摄像头应用类型` LONGTEXT,
    `A端是否派发工程施工` LONGTEXT,
    `首次发起预约时间` LONGTEXT,
    `A端施工结果` LONGTEXT,
    `宽带账号` LONGTEXT,
    `A端施工耗时` LONGTEXT,
    `装维开通(安装)调试服务` LONGTEXT,
    `A端施工费用` LONGTEXT,
    `装维拆机服务` LONGTEXT,
    `装维移机服务产品` LONGTEXT,
    `个性化施工人天` LONGTEXT,
    `前台下单时间` LONGTEXT,
    `工程施工处理人` LONGTEXT,
    `工程施工处理人电话` LONGTEXT,
    `组织现网变更处理人` LONGTEXT,
    `组织现网变更处理人电话` LONGTEXT,
    `资源录入处理人` LONGTEXT,
    `资源录入处理人电话` LONGTEXT,
    `工单回复处理人` LONGTEXT,
    `工单回复处理人电话` LONGTEXT,
    `是否团单` LONGTEXT,
    `是否存在关联工单` LONGTEXT,
    `归档处理人` LONGTEXT,
    `归档处理人电话` LONGTEXT,
    PRIMARY KEY (`订单号`)
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `orch_opening_version` (
    version_id BIGINT PRIMARY KEY AUTO_INCREMENT,
    source_record_id VARCHAR(255) COLLATE utf8mb4_bin NOT NULL,
    run_id VARCHAR(80) NOT NULL,
    row_hash CHAR(64) NOT NULL,
    source_data LONGTEXT NOT NULL,
    observed_at VARCHAR(40) NOT NULL,
    UNIQUE KEY uk_version_record_hash (source_record_id, row_hash),
    KEY idx_version_run (run_id),
    FOREIGN KEY (run_id) REFERENCES etl_run(run_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `orch_install` (
    `订单号` VARCHAR(255) COLLATE utf8mb4_bin NOT NULL,
    `主题` LONGTEXT,
    `订单创建时间` LONGTEXT,
    `订单状态` LONGTEXT,
    `地市` LONGTEXT,
    `区县名称` LONGTEXT,
    `是否点金工单` LONGTEXT,
    `是否快装` LONGTEXT,
    `业务分类` LONGTEXT,
    `业务类型` LONGTEXT,
    `产品名称` LONGTEXT,
    `订单类型` LONGTEXT,
    `调整类型` LONGTEXT,
    `需求网络维护等级` LONGTEXT,
    `产品实例编号` LONGTEXT,
    `专线编号` LONGTEXT,
    `带宽` LONGTEXT,
    `上行带宽` LONGTEXT,
    `上网用途` LONGTEXT,
    `CRM工单号` LONGTEXT,
    `是否撤单重录` LONGTEXT,
    `当前环节` LONGTEXT,
    `当前处理组` LONGTEXT,
    `预约上门时间` LONGTEXT,
    `联调测试时间` LONGTEXT,
    `是否超时` LONGTEXT,
    `超时时间` LONGTEXT,
    `首次派单时间` LONGTEXT,
    `首次考核超时时限` LONGTEXT,
    `考核超时时限` LONGTEXT,
    `工单持续时长` LONGTEXT,
    `当前环节开始时间` LONGTEXT,
    `当前环节持续时长` LONGTEXT,
    `剩余时间` LONGTEXT,
    `工单报结时间` LONGTEXT,
    `订单结束时间` LONGTEXT,
    `订单来源` LONGTEXT,
    `融合工单号` LONGTEXT,
    `客户名称` LONGTEXT,
    `客户编码` LONGTEXT,
    `客户经理` LONGTEXT,
    `集客部联系人联系电话` LONGTEXT,
    `受理人` LONGTEXT,
    `受理人电话` LONGTEXT,
    `报结人` LONGTEXT,
    `报结人电话` LONGTEXT,
    `边缘云专线/三方云专线类型` LONGTEXT,
    `集团客户业务联系人` LONGTEXT,
    `集团客户业务联系人电话` LONGTEXT,
    `集团客户技术联系人` LONGTEXT,
    `集团客户技术联系人电话` LONGTEXT,
    `业务接入标准地址` LONGTEXT,
    `市场网格` LONGTEXT,
    `业务受理耗时` LONGTEXT,
    `方案设计耗时` LONGTEXT,
    `方案审批耗时` LONGTEXT,
    `现网变更耗时` LONGTEXT,
    `业务验证耗时` LONGTEXT,
    `归档报结耗时` LONGTEXT,
    `方案设计处理人` LONGTEXT,
    `资源查询受理人` LONGTEXT,
    `方案审核处理人` LONGTEXT,
    `资源分配受理人` LONGTEXT,
    `配置激活处理人` LONGTEXT,
    `客户端安装处理人` LONGTEXT,
    `业务验证处理人` LONGTEXT,
    `开通结果审核处理人` LONGTEXT,
    `是否派发工程施工` LONGTEXT,
    `施工结果` LONGTEXT,
    `施工耗时` LONGTEXT,
    `未自动受理原因` LONGTEXT,
    `施工费用` LONGTEXT,
    `业务受理自动化失败原因` LONGTEXT,
    `A端专线接入区县` LONGTEXT,
    `方案设计自动化失败原因` LONGTEXT,
    `A端业务接入标准地址` LONGTEXT,
    `资源查询自动化失败原因` LONGTEXT,
    `摄像头应用类型` LONGTEXT,
    `A端是否派发工程施工` LONGTEXT,
    `资源分配自动化失败原因` LONGTEXT,
    `首次发起预约时间` LONGTEXT,
    `A端施工结果` LONGTEXT,
    `配置激活自动化失败原因` LONGTEXT,
    `宽带账号` LONGTEXT,
    `A端施工耗时` LONGTEXT,
    `开通结果审核自动化失败原因` LONGTEXT,
    `装维开通(安装)调试服务` LONGTEXT,
    `A端施工费用` LONGTEXT,
    `竣工报结自动化失败原因` LONGTEXT,
    `装维拆机服务` LONGTEXT,
    `点金剩余时间` LONGTEXT,
    `装维移机服务产品` LONGTEXT,
    `场所类别` LONGTEXT,
    `个性化施工人天` LONGTEXT,
    `前台下单时间` LONGTEXT,
    `细分客群类别` LONGTEXT,
    `工程施工处理人` LONGTEXT,
    `工程施工处理人电话` LONGTEXT,
    `组织现网变更处理人` LONGTEXT,
    `组织现网变更处理人电话` LONGTEXT,
    `资源录入处理人` LONGTEXT,
    `资源录入处理人电话` LONGTEXT,
    `工单回复处理人` LONGTEXT,
    `工单回复处理人电话` LONGTEXT,
    `是否团单` LONGTEXT,
    `是否存在关联工单` LONGTEXT,
    `归档处理人` LONGTEXT,
    `归档处理人电话` LONGTEXT,
    PRIMARY KEY (`订单号`)
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `orch_install_version` (
    version_id BIGINT PRIMARY KEY AUTO_INCREMENT,
    source_record_id VARCHAR(255) COLLATE utf8mb4_bin NOT NULL,
    run_id VARCHAR(80) NOT NULL,
    row_hash CHAR(64) NOT NULL,
    source_data LONGTEXT NOT NULL,
    observed_at VARCHAR(40) NOT NULL,
    UNIQUE KEY uk_version_record_hash (source_record_id, row_hash),
    KEY idx_version_run (run_id),
    FOREIGN KEY (run_id) REFERENCES etl_run(run_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `integration_opening` (
    `工单号` VARCHAR(255) COLLATE utf8mb4_bin NOT NULL,
    `工单主题` LONGTEXT,
    `工单数据来源` LONGTEXT,
    `上游工单号` LONGTEXT,
    `派单时间` LONGTEXT,
    `受理部门` LONGTEXT,
    `工单流向` LONGTEXT,
    `地市` LONGTEXT,
    `区县` LONGTEXT,
    `业务类型` LONGTEXT,
    `工单类型` LONGTEXT,
    `调整类型` LONGTEXT,
    `是否存在关联工单` LONGTEXT,
    `关联工单号` LONGTEXT,
    `工单状态` LONGTEXT,
    `是否超时` LONGTEXT,
    `是否撤单重录` LONGTEXT,
    `首次派单时间` LONGTEXT,
    `首次考核超时时限` LONGTEXT,
    `考核超时时限` LONGTEXT,
    `工单是否及时开通` LONGTEXT,
    `业务开通时间(h)` LONGTEXT,
    `工单历时/小时` LONGTEXT,
    `工单处理时限` LONGTEXT,
    `工单结束时间` LONGTEXT,
    `业务套餐类型` LONGTEXT,
    `业务保障等级` LONGTEXT,
    `计费号/产品实例编号` LONGTEXT,
    `是否派发工程施工` LONGTEXT,
    PRIMARY KEY (`工单号`)
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `integration_opening_version` (
    version_id BIGINT PRIMARY KEY AUTO_INCREMENT,
    source_record_id VARCHAR(255) COLLATE utf8mb4_bin NOT NULL,
    run_id VARCHAR(80) NOT NULL,
    row_hash CHAR(64) NOT NULL,
    source_data LONGTEXT NOT NULL,
    observed_at VARCHAR(40) NOT NULL,
    UNIQUE KEY uk_version_record_hash (source_record_id, row_hash),
    KEY idx_version_run (run_id),
    FOREIGN KEY (run_id) REFERENCES etl_run(run_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `eoms_complaint` (
    `id` LONGTEXT,
    `工单号` VARCHAR(255) COLLATE utf8mb4_bin NOT NULL,
    `工单主题` LONGTEXT,
    `派单时间` LONGTEXT,
    `updateTime` LONGTEXT,
    `完成时间` LONGTEXT,
    `处理超时时限` LONGTEXT,
    `status` LONGTEXT,
    `工单状态` LONGTEXT,
    `客服流水号` LONGTEXT,
    `procName` LONGTEXT,
    `集团名称` LONGTEXT,
    `集团编号` LONGTEXT,
    `groupcliNo` LONGTEXT,
    `所属区县` LONGTEXT,
    `所属地市` LONGTEXT,
    `city` LONGTEXT,
    `计费号码` LONGTEXT,
    `计费号码补位来源` LONGTEXT,
    `jtCalle` LONGTEXT,
    `手机号码` LONGTEXT,
    `jtLinkman` LONGTEXT,
    `jtLinkmanPhone` LONGTEXT,
    `归属地` LONGTEXT,
    `jtCustomerType` LONGTEXT,
    `客户类型` LONGTEXT,
    `blocGrade` LONGTEXT,
    `集团等级` LONGTEXT,
    `isVipcustomer` LONGTEXT,
    `VIP等级` LONGTEXT,
    `busiAssurLevel` LONGTEXT,
    `业务保障等级` LONGTEXT,
    `业务覆盖范围` LONGTEXT,
    `busitype` LONGTEXT,
    `业务类别` LONGTEXT,
    `lastbusitype` LONGTEXT,
    `busiTypeArr` LONGTEXT,
    `zqcomplaintType` LONGTEXT,
    `投诉类型` LONGTEXT,
    `businessType` LONGTEXT,
    `业务类型` LONGTEXT,
    `isSelfbuild` LONGTEXT,
    `是否多部门处理` LONGTEXT,
    `dataOrigin` LONGTEXT,
    `投诉内容` LONGTEXT,
    `退单附加说明` LONGTEXT,
    `附加说明` LONGTEXT,
    `附加报结信息` LONGTEXT,
    `新客服流水号` LONGTEXT,
    `客服受理时间` LONGTEXT,
    `派单时间_系统` LONGTEXT,
    `专线编号` LONGTEXT,
    `cpAscribe` LONGTEXT,
    `投诉归因` LONGTEXT,
    `最后处理人` LONGTEXT,
    `更新部门` LONGTEXT,
    `客服派单人工号` LONGTEXT,
    `createByDeptname` LONGTEXT,
    `处理人` LONGTEXT,
    `当前责任班组` LONGTEXT,
    `taskName` LONGTEXT,
    `taskDefId` LONGTEXT,
    `dealId` LONGTEXT,
    `查询索引` LONGTEXT,
    `客户经理` LONGTEXT,
    `客户经理电话` LONGTEXT,
    `zBusinessOwnera` LONGTEXT,
    `zBusinessOwneraTel` LONGTEXT,
    `zBusinessOwnerb` LONGTEXT,
    `zBusinessOwnerbTel` LONGTEXT,
    `所属市场网格` LONGTEXT,
    `流程状态` LONGTEXT,
    `当前环节` LONGTEXT,
    `告警匹配结果` LONGTEXT,
    `受理时间` LONGTEXT,
    `最后处理时间` LONGTEXT,
    `首次转派时间` LONGTEXT,
    `退单原因` LONGTEXT,
    `退单备注` LONGTEXT,
    `是否退单` LONGTEXT,
    `处理班组` LONGTEXT,
    `受理班组` LONGTEXT,
    `受理人` LONGTEXT,
    `质检部门` LONGTEXT,
    `质检人` LONGTEXT,
    `最后处理班组` LONGTEXT,
    `结单人` LONGTEXT,
    `结单时间` LONGTEXT,
    `结单意见` LONGTEXT,
    `处理备注` LONGTEXT,
    `解决情况` LONGTEXT,
    `重复派单次数` LONGTEXT,
    `下一环节区县` LONGTEXT,
    `下一环节地市` LONGTEXT,
    `nextTaskInfo.sheetType` LONGTEXT,
    `nextTaskInfo.queryIndex` LONGTEXT,
    `nextTaskInfo.industryCustType` LONGTEXT,
    `nextTaskInfo.strategicCustTypeFL` LONGTEXT,
    `nextTaskInfo.vipCustType` LONGTEXT,
    `nextTaskInfo.vipCustomTypeName` LONGTEXT,
    `finishSuggestion` LONGTEXT,
    `完成建议` LONGTEXT,
    `slaLevel` LONGTEXT,
    `SLA等级` LONGTEXT,
    `受理方式` LONGTEXT,
    `pjProjectCity` LONGTEXT,
    `pjProjectCounty` LONGTEXT,
    `netCode` LONGTEXT,
    `合作模式` LONGTEXT,
    PRIMARY KEY (`工单号`)
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `eoms_complaint_version` (
    version_id BIGINT PRIMARY KEY AUTO_INCREMENT,
    source_record_id VARCHAR(255) COLLATE utf8mb4_bin NOT NULL,
    run_id VARCHAR(80) NOT NULL,
    row_hash CHAR(64) NOT NULL,
    source_data LONGTEXT NOT NULL,
    observed_at VARCHAR(40) NOT NULL,
    UNIQUE KEY uk_version_record_hash (source_record_id, row_hash),
    KEY idx_version_run (run_id),
    FOREIGN KEY (run_id) REFERENCES etl_run(run_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `youshu_install` (
    `地市` LONGTEXT,
    `区县` LONGTEXT,
    `市场网格` LONGTEXT,
    `班组` LONGTEXT,
    `微格名称` LONGTEXT,
    `宽带账号` LONGTEXT,
    `工单id` VARCHAR(255) COLLATE utf8mb4_bin NOT NULL,
    `工单类型` LONGTEXT,
    `动作类型` LONGTEXT,
    `业务类型` LONGTEXT,
    `渠道名称` LONGTEXT,
    `产品附属属性` LONGTEXT,
    `宽带类型` LONGTEXT,
    `工单状态` LONGTEXT,
    `受理时间` LONGTEXT,
    `派单时间` LONGTEXT,
    `工单状态时间` LONGTEXT,
    `是否超时` LONGTEXT,
    `退单原因-自定义分类` LONGTEXT,
    `退单原因` LONGTEXT,
    `退单状态` LONGTEXT,
    `退撤标识` LONGTEXT,
    `调度退单原因` LONGTEXT,
    `覆盖场景` LONGTEXT,
    `沿街商铺` LONGTEXT,
    `装维电话` LONGTEXT,
    `装维工号` LONGTEXT,
    `操作人` LONGTEXT,
    `同新装同账号的最终工单状态` LONGTEXT,
    `是否最终工单` LONGTEXT,
    `工单受理时间是否符合` LONGTEXT,
    `工单状态时间是否符合` LONGTEXT,
    `用户电话` LONGTEXT,
    PRIMARY KEY (`工单id`)
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `youshu_install_version` (
    version_id BIGINT PRIMARY KEY AUTO_INCREMENT,
    source_record_id VARCHAR(255) COLLATE utf8mb4_bin NOT NULL,
    run_id VARCHAR(80) NOT NULL,
    row_hash CHAR(64) NOT NULL,
    source_data LONGTEXT NOT NULL,
    observed_at VARCHAR(40) NOT NULL,
    UNIQUE KEY uk_version_record_hash (source_record_id, row_hash),
    KEY idx_version_run (run_id),
    FOREIGN KEY (run_id) REFERENCES etl_run(run_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `youshu_complaint` (
    `地市` LONGTEXT,
    `区县` LONGTEXT,
    `工单号` VARCHAR(255) COLLATE utf8mb4_bin NOT NULL,
    `客服流水号` LONGTEXT,
    `宽带账号` LONGTEXT,
    `装维工号` LONGTEXT,
    `班组名称` LONGTEXT,
    `是否小微投诉` LONGTEXT,
    `是否酒店类投诉` LONGTEXT,
    `是否夜间(受理时间)` LONGTEXT,
    `小微处理时长(待配置派发-报结/now)` LONGTEXT,
    `小微酒店处理时长(待配置派发-报结/now)` LONGTEXT,
    `受理时间` LONGTEXT,
    `派单时间` LONGTEXT,
    `是否及时` LONGTEXT,
    `待配置派发时间` LONGTEXT,
    `实际首次进入已配置派发时间` LONGTEXT,
    `报结时间` LONGTEXT,
    `工单状态` LONGTEXT,
    `主题` LONGTEXT,
    `集团报结意见` LONGTEXT,
    PRIMARY KEY (`工单号`)
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `youshu_complaint_version` (
    version_id BIGINT PRIMARY KEY AUTO_INCREMENT,
    source_record_id VARCHAR(255) COLLATE utf8mb4_bin NOT NULL,
    run_id VARCHAR(80) NOT NULL,
    row_hash CHAR(64) NOT NULL,
    source_data LONGTEXT NOT NULL,
    observed_at VARCHAR(40) NOT NULL,
    UNIQUE KEY uk_version_record_hash (source_record_id, row_hash),
    KEY idx_version_run (run_id),
    FOREIGN KEY (run_id) REFERENCES etl_run(run_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
-- END FIXED RAW TABLES

CREATE TABLE IF NOT EXISTS metric_run (
    metric_run_id VARCHAR(80) PRIMARY KEY,
    metric_code VARCHAR(120) NOT NULL,
    metric_version VARCHAR(80) NOT NULL,
    period_start VARCHAR(10) NOT NULL,
    period_end VARCHAR(10) NOT NULL,
    started_at VARCHAR(40) NOT NULL,
    finished_at VARCHAR(40),
    status VARCHAR(16) NOT NULL,
    source_runs LONGTEXT NOT NULL,
    error_message TEXT,
    KEY idx_metric_run_code_period (metric_code, period_start, period_end, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `result_terminal_recovery` (
    result_id BIGINT PRIMARY KEY AUTO_INCREMENT,
    metric_run_id VARCHAR(80) NOT NULL,
    metric_code VARCHAR(120) NOT NULL,
    dimension_type VARCHAR(120) NOT NULL,
    dimension_value LONGTEXT NOT NULL,
    dimension_value_hash CHAR(64) GENERATED ALWAYS AS (SHA2(dimension_value, 256)) STORED,
    `sheet_name` VARCHAR(255) GENERATED ALWAYS AS (JSON_UNQUOTE(JSON_EXTRACT(dimension_value, '$.sheet'))) STORED, `summary_type` VARCHAR(255) GENERATED ALWAYS AS (JSON_UNQUOTE(JSON_EXTRACT(dimension_value, '$.table'))) STORED, `row_index` INT GENERATED ALWAYS AS (JSON_UNQUOTE(JSON_EXTRACT(dimension_value, '$.row_index'))) STORED, `column_index` INT GENERATED ALWAYS AS (JSON_UNQUOTE(JSON_EXTRACT(dimension_value, '$.column_index'))) STORED, `label_column` VARCHAR(255) GENERATED ALWAYS AS (JSON_UNQUOTE(JSON_EXTRACT(dimension_value, '$.label_column'))) STORED, `row_label` VARCHAR(255) GENERATED ALWAYS AS (JSON_UNQUOTE(JSON_EXTRACT(dimension_value, '$.label'))) STORED, `column_label` VARCHAR(255) GENERATED ALWAYS AS (JSON_UNQUOTE(JSON_EXTRACT(dimension_value, '$.column'))) STORED,
    numerator DOUBLE,
    denominator DOUBLE,
    metric_value DOUBLE,
    UNIQUE KEY uk_result_dimension (metric_run_id, metric_code, dimension_type, dimension_value_hash),
    FOREIGN KEY (metric_run_id) REFERENCES metric_run(metric_run_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `result_opening_withdrawal` (
    result_id BIGINT PRIMARY KEY AUTO_INCREMENT,
    metric_run_id VARCHAR(80) NOT NULL,
    metric_code VARCHAR(120) NOT NULL,
    dimension_type VARCHAR(120) NOT NULL,
    dimension_value LONGTEXT NOT NULL,
    dimension_value_hash CHAR(64) GENERATED ALWAYS AS (SHA2(dimension_value, 256)) STORED,
    `scope` VARCHAR(255) GENERATED ALWAYS AS (JSON_UNQUOTE(JSON_EXTRACT(dimension_value, '$.scope'))) STORED, `city` VARCHAR(255) GENERATED ALWAYS AS (JSON_UNQUOTE(JSON_EXTRACT(dimension_value, '$.city'))) STORED, `business_type` VARCHAR(255) GENERATED ALWAYS AS (JSON_UNQUOTE(JSON_EXTRACT(dimension_value, '$.business_type'))) STORED,
    numerator DOUBLE,
    denominator DOUBLE,
    metric_value DOUBLE,
    UNIQUE KEY uk_result_dimension (metric_run_id, metric_code, dimension_type, dimension_value_hash),
    FOREIGN KEY (metric_run_id) REFERENCES metric_run(metric_run_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `result_dedicated_line_install_fault` (
    result_id BIGINT PRIMARY KEY AUTO_INCREMENT,
    metric_run_id VARCHAR(80) NOT NULL,
    metric_code VARCHAR(120) NOT NULL,
    dimension_type VARCHAR(120) NOT NULL,
    dimension_value LONGTEXT NOT NULL,
    dimension_value_hash CHAR(64) GENERATED ALWAYS AS (SHA2(dimension_value, 256)) STORED,
    `scope` VARCHAR(255) GENERATED ALWAYS AS (JSON_UNQUOTE(JSON_EXTRACT(dimension_value, '$.scope'))) STORED, `city` VARCHAR(255) GENERATED ALWAYS AS (JSON_UNQUOTE(JSON_EXTRACT(dimension_value, '$.city'))) STORED, `business_type` VARCHAR(255) GENERATED ALWAYS AS (JSON_UNQUOTE(JSON_EXTRACT(dimension_value, '$.business_type'))) STORED,
    numerator DOUBLE,
    denominator DOUBLE,
    metric_value DOUBLE,
    UNIQUE KEY uk_result_dimension (metric_run_id, metric_code, dimension_type, dimension_value_hash),
    FOREIGN KEY (metric_run_id) REFERENCES metric_run(metric_run_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `result_qikuan_install_fault` (
    result_id BIGINT PRIMARY KEY AUTO_INCREMENT,
    metric_run_id VARCHAR(80) NOT NULL,
    metric_code VARCHAR(120) NOT NULL,
    dimension_type VARCHAR(120) NOT NULL,
    dimension_value LONGTEXT NOT NULL,
    dimension_value_hash CHAR(64) GENERATED ALWAYS AS (SHA2(dimension_value, 256)) STORED,
    `scope` VARCHAR(255) GENERATED ALWAYS AS (JSON_UNQUOTE(JSON_EXTRACT(dimension_value, '$.scope'))) STORED, `city` VARCHAR(255) GENERATED ALWAYS AS (JSON_UNQUOTE(JSON_EXTRACT(dimension_value, '$.city'))) STORED, `business_type` VARCHAR(255) GENERATED ALWAYS AS (JSON_UNQUOTE(JSON_EXTRACT(dimension_value, '$.business_type'))) STORED,
    numerator DOUBLE,
    denominator DOUBLE,
    metric_value DOUBLE,
    UNIQUE KEY uk_result_dimension (metric_run_id, metric_code, dimension_type, dimension_value_hash),
    FOREIGN KEY (metric_run_id) REFERENCES metric_run(metric_run_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `result_commercial_install_fault` (
    result_id BIGINT PRIMARY KEY AUTO_INCREMENT,
    metric_run_id VARCHAR(80) NOT NULL,
    metric_code VARCHAR(120) NOT NULL,
    dimension_type VARCHAR(120) NOT NULL,
    dimension_value LONGTEXT NOT NULL,
    dimension_value_hash CHAR(64) GENERATED ALWAYS AS (SHA2(dimension_value, 256)) STORED,
    `scope` VARCHAR(255) GENERATED ALWAYS AS (JSON_UNQUOTE(JSON_EXTRACT(dimension_value, '$.scope'))) STORED, `city` VARCHAR(255) GENERATED ALWAYS AS (JSON_UNQUOTE(JSON_EXTRACT(dimension_value, '$.city'))) STORED, `business_type` VARCHAR(255) GENERATED ALWAYS AS (JSON_UNQUOTE(JSON_EXTRACT(dimension_value, '$.business_type'))) STORED,
    numerator DOUBLE,
    denominator DOUBLE,
    metric_value DOUBLE,
    UNIQUE KEY uk_result_dimension (metric_run_id, metric_code, dimension_type, dimension_value_hash),
    FOREIGN KEY (metric_run_id) REFERENCES metric_run(metric_run_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `result_dedicated_line_repeat_complaint` (
    result_id BIGINT PRIMARY KEY AUTO_INCREMENT,
    metric_run_id VARCHAR(80) NOT NULL,
    metric_code VARCHAR(120) NOT NULL,
    dimension_type VARCHAR(120) NOT NULL,
    dimension_value LONGTEXT NOT NULL,
    dimension_value_hash CHAR(64) GENERATED ALWAYS AS (SHA2(dimension_value, 256)) STORED,
    `scope` VARCHAR(255) GENERATED ALWAYS AS (JSON_UNQUOTE(JSON_EXTRACT(dimension_value, '$.scope'))) STORED, `city` VARCHAR(255) GENERATED ALWAYS AS (JSON_UNQUOTE(JSON_EXTRACT(dimension_value, '$.city'))) STORED, `business_type` VARCHAR(255) GENERATED ALWAYS AS (JSON_UNQUOTE(JSON_EXTRACT(dimension_value, '$.business_type'))) STORED,
    numerator DOUBLE,
    denominator DOUBLE,
    metric_value DOUBLE,
    UNIQUE KEY uk_result_dimension (metric_run_id, metric_code, dimension_type, dimension_value_hash),
    FOREIGN KEY (metric_run_id) REFERENCES metric_run(metric_run_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `result_qianliyan_repeat_complaint` (
    result_id BIGINT PRIMARY KEY AUTO_INCREMENT,
    metric_run_id VARCHAR(80) NOT NULL,
    metric_code VARCHAR(120) NOT NULL,
    dimension_type VARCHAR(120) NOT NULL,
    dimension_value LONGTEXT NOT NULL,
    dimension_value_hash CHAR(64) GENERATED ALWAYS AS (SHA2(dimension_value, 256)) STORED,
    `scope` VARCHAR(255) GENERATED ALWAYS AS (JSON_UNQUOTE(JSON_EXTRACT(dimension_value, '$.scope'))) STORED, `city` VARCHAR(255) GENERATED ALWAYS AS (JSON_UNQUOTE(JSON_EXTRACT(dimension_value, '$.city'))) STORED, `business_type` VARCHAR(255) GENERATED ALWAYS AS (JSON_UNQUOTE(JSON_EXTRACT(dimension_value, '$.business_type'))) STORED,
    numerator DOUBLE,
    denominator DOUBLE,
    metric_value DOUBLE,
    UNIQUE KEY uk_result_dimension (metric_run_id, metric_code, dimension_type, dimension_value_hash),
    FOREIGN KEY (metric_run_id) REFERENCES metric_run(metric_run_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `result_orchestration_opening` (
    result_id BIGINT PRIMARY KEY AUTO_INCREMENT,
    metric_run_id VARCHAR(80) NOT NULL,
    metric_code VARCHAR(120) NOT NULL,
    dimension_type VARCHAR(120) NOT NULL,
    dimension_value LONGTEXT NOT NULL,
    dimension_value_hash CHAR(64) GENERATED ALWAYS AS (SHA2(dimension_value, 256)) STORED,
    `month` VARCHAR(255) GENERATED ALWAYS AS (JSON_UNQUOTE(JSON_EXTRACT(dimension_value, '$.month'))) STORED, `comparison_month` VARCHAR(255) GENERATED ALWAYS AS (JSON_UNQUOTE(JSON_EXTRACT(dimension_value, '$.comparison_month'))) STORED, `end_month` VARCHAR(255) GENERATED ALWAYS AS (JSON_UNQUOTE(JSON_EXTRACT(dimension_value, '$.end_month'))) STORED, `city` VARCHAR(255) GENERATED ALWAYS AS (JSON_UNQUOTE(JSON_EXTRACT(dimension_value, '$.city'))) STORED, `county` VARCHAR(255) GENERATED ALWAYS AS (JSON_UNQUOTE(JSON_EXTRACT(dimension_value, '$.county'))) STORED, `product` VARCHAR(255) GENERATED ALWAYS AS (JSON_UNQUOTE(JSON_EXTRACT(dimension_value, '$.product'))) STORED, `stage` VARCHAR(255) GENERATED ALWAYS AS (JSON_UNQUOTE(JSON_EXTRACT(dimension_value, '$.stage'))) STORED, `source_field` VARCHAR(255) GENERATED ALWAYS AS (JSON_UNQUOTE(JSON_EXTRACT(dimension_value, '$.field'))) STORED, `automatic_value` VARCHAR(255) GENERATED ALWAYS AS (JSON_UNQUOTE(JSON_EXTRACT(dimension_value, '$.automatic_value'))) STORED,
    numerator DOUBLE,
    denominator DOUBLE,
    metric_value DOUBLE,
    UNIQUE KEY uk_result_dimension (metric_run_id, metric_code, dimension_type, dimension_value_hash),
    FOREIGN KEY (metric_run_id) REFERENCES metric_run(metric_run_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ads_metric_detail (
    detail_id BIGINT PRIMARY KEY AUTO_INCREMENT,
    metric_run_id VARCHAR(80) NOT NULL,
    metric_code VARCHAR(120) NOT NULL,
    detail_role VARCHAR(32) NOT NULL,
    source_dataset_code VARCHAR(80) NOT NULL,
    source_record_id VARCHAR(255) NOT NULL,
    dimension_value LONGTEXT NOT NULL,
    dimension_value_hash CHAR(64) GENERATED ALWAYS AS (SHA2(dimension_value, 256)) STORED,
    detail_data LONGTEXT NOT NULL,
    UNIQUE KEY uk_ads_metric_detail (
        metric_run_id, metric_code, detail_role,
        source_dataset_code, source_record_id, dimension_value_hash
    ),
    KEY idx_ads_metric_detail_run_role (metric_run_id, metric_code, detail_role),
    CONSTRAINT fk_ads_detail_metric_run FOREIGN KEY (metric_run_id) REFERENCES metric_run(metric_run_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS orch_opening_monthly_summary (
    summary_id BIGINT PRIMARY KEY AUTO_INCREMENT,
    month VARCHAR(7) NOT NULL,
    metric_version VARCHAR(80) NOT NULL,
    metric_code VARCHAR(120) NOT NULL,
    dimension_type VARCHAR(120) NOT NULL,
    dimension_value LONGTEXT NOT NULL,
    dimension_value_hash CHAR(64) GENERATED ALWAYS AS (SHA2(dimension_value, 256)) STORED,
    numerator DOUBLE,
    denominator DOUBLE,
    metric_value DOUBLE,
    source_metric_run_id VARCHAR(80) NOT NULL,
    updated_at VARCHAR(40) NOT NULL,
    UNIQUE KEY uk_orch_opening_monthly_summary (
        month, metric_version, metric_code, dimension_type, dimension_value_hash
    ),
    KEY idx_orch_opening_monthly_summary_month (month, metric_version),
    CONSTRAINT fk_orch_summary_metric_run FOREIGN KEY (source_metric_run_id) REFERENCES metric_run(metric_run_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS orch_opening_monthly_quality (
    month VARCHAR(7) NOT NULL,
    metric_version VARCHAR(80) NOT NULL,
    database_rows BIGINT NOT NULL,
    rows_missing_order_month BIGINT NOT NULL,
    source_metric_run_id VARCHAR(80) NOT NULL,
    updated_at VARCHAR(40) NOT NULL,
    PRIMARY KEY (month, metric_version),
    CONSTRAINT fk_orch_quality_metric_run FOREIGN KEY (source_metric_run_id) REFERENCES metric_run(metric_run_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS data_retention_purge (
    purge_id BIGINT PRIMARY KEY AUTO_INCREMENT,
    dataset_code VARCHAR(80) NOT NULL,
    period_start VARCHAR(10) NOT NULL,
    period_end VARCHAR(10) NOT NULL,
    purged_at VARCHAR(40) NOT NULL,
    archive_file TEXT NOT NULL,
    rows_purged BIGINT NOT NULL,
    KEY idx_retention_dataset_period (dataset_code, period_start, period_end)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS raw_record_audit (
    dataset_code VARCHAR(80) NOT NULL,
    source_record_id VARCHAR(255) COLLATE utf8mb4_bin NOT NULL,
    row_hash CHAR(64) NOT NULL,
    first_run_id VARCHAR(80) NOT NULL,
    last_run_id VARCHAR(80) NOT NULL,
    first_seen_at VARCHAR(40) NOT NULL,
    last_seen_at VARCHAR(40) NOT NULL,
    PRIMARY KEY (dataset_code, source_record_id),
    KEY idx_raw_audit_last_run (last_run_id),
    FOREIGN KEY (first_run_id) REFERENCES etl_run(run_id),
    FOREIGN KEY (last_run_id) REFERENCES etl_run(run_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS raw_import_error (
    error_id BIGINT PRIMARY KEY AUTO_INCREMENT,
    run_id VARCHAR(80) NOT NULL,
    source_row_number BIGINT NOT NULL,
    source_record_id VARCHAR(255),
    error_message TEXT NOT NULL,
    FOREIGN KEY (run_id) REFERENCES etl_run(run_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS raw_period_batch (
    dataset_code VARCHAR(80) NOT NULL,
    period_start VARCHAR(10) NOT NULL,
    period_end VARCHAR(10) NOT NULL,
    run_id VARCHAR(80) NOT NULL,
    content_hash CHAR(64) NOT NULL,
    row_count BIGINT NOT NULL,
    PRIMARY KEY (dataset_code, period_start, period_end),
    FOREIGN KEY (run_id) REFERENCES etl_run(run_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS raw_period_row (
    dataset_code VARCHAR(80) NOT NULL,
    period_start VARCHAR(10) NOT NULL,
    period_end VARCHAR(10) NOT NULL,
    source_row_number BIGINT NOT NULL,
    row_id BIGINT NOT NULL,
    PRIMARY KEY (dataset_code, period_start, period_end, source_row_number),
    KEY idx_raw_period_row_id (dataset_code, row_id),
    UNIQUE KEY uk_raw_period_row_once (dataset_code, period_start, period_end, row_id),
    FOREIGN KEY (dataset_code, period_start, period_end)
        REFERENCES raw_period_batch(dataset_code, period_start, period_end)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
